export const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'] as const;
export const SIZE_UNITS = ['B', 'KB', 'MB', 'GB'] as const;
export const EMOJIS = {
  SUCCESS: '✅',
  ERROR: '❌',
  WARNING: '🚨',
  INFO: 'ℹ️',
  VERSION: '🆚',
  DEBUG: '🐛',
  TABLE: '📊',
  GROUP: '📋',
  ROCKET: '🚀',
  HOUSE: '🏠',
  PACKAGE: '📦',
  MEMO: '📝',
  HAMMER: '🔨',
  TEST: '🧪',
  NAIL: '💅',
  MAGNIFIER: '🔍',
  LABEL: '🏷️',
  FLOPPY: '💾',
  FOLDER: '📁',
  INCREMENT: '🔄',
  CHANGELOG: '📝',
  TAG: '🏷️',
  SETTINGS: '⚙️',
  CURRENT: '⭐',
  CLOCK: '⏰',
  CELEBRATE: '🎉',
  QUESTION: '❓',
  RETRY: '🔁',
  UP: '⬆️',
} as const;
