#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

bun test
npx lint-staged
bun run update-version

# If there are any changes from lint-staged, amend them to the current commit
if git diff --cached --quiet; then
  echo "No changes to amend"
else
  git commit --amend --no-edit
fi
